{
    'name' : 'Hospital Management',
    'version' : '1.1',
    'summary': 'Hospital Management System',
    'sequence': -100,
    'description': """Hospital Management System""",
    'category': 'Productivity',
    'website': 'https://www.odoomates.tech',
    'depends' : [
        'sale',
        'mail',
        'website_slides',
        'hr',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'wizards/wizards_view.xml',
        'views/patient.xml',
        'views/sale.xml',
        'views/kids_view.xml',
        'views/patient_gender_view.xml',
        'report/report.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
